name: Update Dispatchwrapparr Playlist

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch: 
  repository_dispatch:
    types: [loop_trigger] # This allows the file to trigger itself

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    
    concurrency:
      group: playlist-loop
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Convert playlist
        run: python convert_to_dispatchwrapparr.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@://github.com"
          git add axis.m3u
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update playlist $(date -u +%Y-%m-%d)"
            git push
          fi

      - name: Cool Down Period
        run: sleep 30

      - name: Trigger Next Loop
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REFRESHER }} # Your updated secret
          event-type: loop_trigger
